version: '3.2'
services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - "POSTGRES_PASSWORD=password"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.4
    ports:
      - "9200:9200"
    environment:
      - "discovery.type=single-node"
      - "xpack.security.enabled=false"
  kibana:
    image: docker.elastic.co/kibana/kibana:7.13.4
    ports:
      - "5601:5601"
    restart: on-failure
    depends_on:
      - elasticsearch
  auction:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
    ports:
      - "8080:8080"
    depends_on:
      - postgres